### ISSUE TITLE
chat server crashes on boot: RedisConnection has no attribute 'pubsub_channels'

### ISSUE THREAD

**Issue by nfirvine** [byronh/dashto.net#1]
Getting the following when I try to start it:

```
python /opt/dashto/src/dashto/chat_server.py -c /opt/dashto/etc/production.ini
Chat server listening on 0.0.0.0:5001...
Subscribed to channel: chan:1
Traceback (most recent call last):
  File "/opt/dashto/src/dashto/chat_server.py", line 23, in <module>
    chat_server.start()
  File "/opt/dashto/src/dashto/dashto/chat/server.py", line 32, in start
    self.loop.run_until_complete(self.publish_handler())
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 236, in _step
    result = coro.send(value)
  File "/opt/dashto/src/dashto/dashto/chat/server.py", line 67, in publish_handler
    message = yield from self.sub.pubsub_channels['chan:1'].get()
AttributeError: 'RedisConnection' object has no attribute 'pubsub_channels'
Task was destroyed but it is pending!
task: <Task pending coro=<_read_data() running at /opt/dashto/lib/python3.4/site-packages/aioredis/connection.py:86> wait_for=<Future pending cb=[Task._wakeup()]> cb=[Future.set_result()]>
Task was destroyed but it is pending!
task: <Task pending coro=<_read_data() running at /opt/dashto/lib/python3.4/site-packages/aioredis/connection.py:86> wait_for=<Future pending cb=[Task._wakeup()]> cb=[Future.set_result()]>
Exception ignored in: <bound method _UnixSelectorEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 361, in __del__
  File "/usr/lib64/python3.4/asyncio/unix_events.py", line 57, in close
  File "/usr/lib64/python3.4/asyncio/unix_events.py", line 138, in remove_signal_handler
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
Task was destroyed but it is pending!
task: <Task pending coro=<_read_data() running at /opt/dashto/lib/python3.4/site-packages/aioredis/connection.py:86> wait_for=<Future pending cb=[Task._wakeup()]> cb=[Future.set_result()]>
Exception ignored in: Exception ignored in: Exception ignored in:
```
# Info

```
pip show hiredis aioredis

---
Metadata-Version: 1.1
Name: hiredis
Version: 0.2.0
Summary: Python wrapper for hiredis
Home-page: https://github.com/redis/hiredis-py
Author: Jan-Erik Rediger, Pieter Noordhuis
Author-email: janerik@fnordig.de, pcnoordhuis@gmail.com
License: BSD
Location: /opt/dashto/lib/python3.4/site-packages
Requires:

---
Metadata-Version: 2.0
Name: aioredis
Version: 0.1.5
Summary: asyncio (PEP 3156) Redis support
Home-page: https://github.com/aio-libs/aioredis
Author: Alexey Popravka
Author-email: alexey.popravka@horsedevel.com
License: MIT
Location: /opt/dashto/lib/python3.4/site-packages
Requires: hiredis
```

Running elasticache Redsi 2.8.19

**Comment by byronh** [comment]
Fixed in ee5d8cf by adding a requirements.txt file.

http://codeinthehole.com/writing/using-pip-and-requirementstxt-to-install-from-the-head-of-a-github-branch/
